exp_name: "wdno_combustion"
gpu: 0
seed: 0
results_path: "./results/"

# data
dataset_name: "combustion"
dataset_root: "/wutailin/real_benchmark/"
num_workers: 12
normalizer: none # none, gaussian, range

# data parameters for training
mask_prob: 0.5
noise_scale: 0.0 # only applicable for numerical data

# model
model_name: "wdno"
checkpoint_path: ./results/wdno/wdno_combustion_numerical_False/2025-09-16_12-34-36/model_64000.pth
dim: 256 
dim_mults: [1, 2]
wave_type: "bior1.3"
pad_mode: "zero"
beta_schedule: "sigmoid" 

# training
is_use_tb: True
scheduler: cosine # step, cosine
step_size: 0 # only applicable for step scheduler
num_update: 100000
train_batch_size: 16
test_batch_size: 64
lr: 0.0001
clip_grad_norm: 1.0 # 0 for no clip

# sampling
sampling_timesteps: 15 # number of sampling timesteps (ddim for faster inference)
ddim_sampling_eta: 1.

# evaluation
N_autoregressive: 1
N_plot: 0