exp_name: deeponet_control
gpu: 0
seed: 0
results_path: ./results/

# data
dataset_name: controlled_cylinder
dataset_root: /wutailin/real_benchmark/
num_workers: 12
normalizer: gaussian   # none, gaussian, range

# data parameters for training
mask_prob: 0.1
noise_scale: 0.1 # only applicable for numerical data

# model
model_name: deeponet
checkpoint_path: ./results/deeponet/deeponet_control_numerical_False/2025-09-08_14-27-56/model_0600.pth
p: 256
dropout_rate: 0.1

# training
is_use_tb: true
scheduler: cosine # step, cosine
step_size: 1000 # only applicable for step scheduler
num_update: 5000
train_batch_size: 64
test_batch_size: 64
lr: 0.00005
clip_grad_norm: 0.

# evaluation
N_autoregressive: 1
N_plot: 1
