exp_name: "fno_foil"
gpu: 0
seed: 0
results_path: "./results/"

# data
dataset_name: "foil"
dataset_root: "/wutailin/real_benchmark/"
num_workers: 12
normalizer: "gaussian" # none, gaussian, range

# data parameters for training
mask_prob: 0.1
noise_scale: 0.1 # only applicable for numerical data

# model
model_name: "fno"
checkpoint_path: ./results/fno/fno_foil_numerical_False/2025-09-17_14-33-39/model_3760.pth
modes1: 4
modes2: 12
modes3: 16
n_layers: 4
width: 64

# training
is_use_tb: True
scheduler: cosine # step, cosine
step_size: 1000 # only applicable for step scheduler
num_update: 4000
train_batch_size: 32
test_batch_size: 64
lr: 0.0001
clip_grad_norm: 0.

# evaluation
N_autoregressive: 1
N_plot: 0