

exp_name: "mwt_foil"
gpu: 0
seed: 0
results_path: "./results/"

# data
dataset_name: "foil"
dataset_root: "/wutailin/real_benchmark/"
num_workers: 12
normalizer: "gaussian" # gaussian, range, none

# data parameters for training
mask_prob: 0.1
noise_scale: 0.1 # only applicable for numerical data


# model
model_name: "mwt"
checkpoint_path: ./results/mwt/mwt_foil_numerical_False/2025-09-18_08-56-12/model_2000.pth

k: 3            # wavelet filter size
alpha: 5        # fourier filter parameter, should be less or equal to T/2
c: 4            # increase factor
nCZ: 4         # number of CZ blocks
L: 0
base: "legendre" # chebyshev


# training
is_use_tb: True
scheduler: cosine # step, cosine
step_size: 1000 # only applicable for step scheduler
num_update: 5000
test_interval: 200
train_batch_size: 32
test_batch_size: 64
lr: 0.0005
clip_grad_norm: 0.

# evaluation
N_autoregressive: 1
N_plot: 1