exp_name: "surrogate_unet_combustion"
gpu: 0
seed: 0
results_path: "./results/"

# data
dataset_name: "combustion"
dataset_root: "/wutailin/real_benchmark/"
num_workers: 10
normalizer: "gaussian"

# model
model_name: "unet"
dim_mults: [1, 2]


# training
is_use_tb: True
scheduler: cosine # step, cosine
step_size: 1000 # only applicable for step scheduler
num_update: 1000
train_batch_size: 2
test_batch_size: 2
lr: 0.0001
clip_grad_norm: 0.
